import { Hero, Layout, PLink } from "@/components";
import EventDetails from "@/components/events/EventDetails";
import { Interestedfn } from "@/components/landing-page";
import Head from "next/head";

export default function Events() {
  return (
    <>
      <Head>
        <title>BPMI | Event</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={""}>
        <Layout>
          <Hero img={"womenwriting"} title={"Event"} />
          {/* <Event /> */}

          <section className="container mx-auto px-4">
            <div className="flex justify-center items-center mb-4 md:mb-12">
              <PLink
                styles="text-gray mr-3 text-[17px] cursor-pointer"
                href="/"
                text="Home"
              />
              /
              <PLink
                styles="text-paleBlue mx-3 text-[17px] cursor-pointer"
                href="/services"
                text="Events"
              />
            </div>
            <EventDetails />
          </section>
          <Interestedfn />
        </Layout>
      </main>
    </>
  );
}
