import { Hero, Layout } from "@/components";
import InputWithLabel from "@/components/Input";
import { eventsApi } from "@/services/api";
import { yupResolver } from "@hookform/resolvers/yup";
import Head from "next/head";
import { useState } from "react";
import { useForm } from "react-hook-form";
import toast from "react-hot-toast";
import * as yup from "yup";

const schema = yup.object({
  name: yup.string().required(),
  phone: yup.string().required(),
  email: yup.string().email().required(),
  highest_qualification: yup.string().required(),
  years_of_pro_expe: yup.string().required(),
  present_job_title: yup.string().required(),
  certifications: yup.mixed(),
});

type FormI = yup.InferType<typeof schema>;
const BecomeAMember = () => {
  const { register, handleSubmit } = useForm<FormI>({
    resolver: yupResolver(schema),
  });

  const [isLoading, setIsLoading] = useState(false);

  const onSubmit = async (data: FormI) => {
    const form = new FormData();

    // Append form data
    form.append("name", data.name);
    form.append("phone", data.phone);
    form.append("email", data.email);
    form.append("highest_qualification", data.highest_qualification);
    form.append("years_of_pro_expe", data.years_of_pro_expe);
    form.append("present_job_title", data.present_job_title);

    // Append certifications if they exist
    if (data.certifications && data.certifications.length > 0) {
      for (let i = 0; i < data.certifications.length; i++) {
        form.append("certifications", data.certifications[i]);
      }
    }

    try {
      setIsLoading(true);
      await eventsApi.submitMembership(form);
      toast.success(
        "Your membership application has been submitted successfully! You will receive a confirmation email shortly."
      );
      // Reset form
      // reset();
    } catch (error: any) {
      console.error("Submission error:", error);
      if (error.response?.data) {
        // Handle DRF validation errors
        if (error.response.data.detail) {
          toast.error(error.response.data.detail);
        } else if (typeof error.response.data === "object") {
          // Handle field-specific validation errors
          const errorMessages = Object.entries(error.response.data)
            .map(([field, errors]: [string, any]) => {
              if (Array.isArray(errors)) {
                return `${field}: ${errors.join(", ")}`;
              }
              return `${field}: ${errors}`;
            })
            .join("\n");
          toast.error(errorMessages);
        } else {
          toast.error(
            error.response.data.message || JSON.stringify(error.response.data)
          );
        }
      } else {
        toast.error(
          "There was an error submitting your application. Please try again later."
        );
      }
    } finally {
      setIsLoading(false);
    }
  };
  return (
    <div>
      <Head>
        <title>BPMI | Become A Member</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={""}>
        <Layout>
          <Hero img={"womenwriting"} title={"Become a member"} />

          <form
            className="max-w-xl mx-auto bg-white p-6 rounded-lg shadow-md"
            onSubmit={handleSubmit(onSubmit)}
          >
            <div className="mb-6">
              <h2 className="text-2xl font-semibold text-gray-800 mb-2">
                Membership Application
              </h2>
              <p className="text-gray-600">
                Please fill out all required fields to submit your membership
                application.
              </p>
            </div>

            <InputWithLabel
              label="Full Name"
              register={register("name")}
              placeholder="Enter your full name"
            />
            <InputWithLabel
              label="Phone Number"
              register={register("phone")}
              placeholder="Enter your phone number"
            />
            <InputWithLabel
              label="Email Address"
              register={register("email")}
              type="email"
              placeholder="Enter your email address"
            />
            <InputWithLabel
              label="Highest Qualification"
              register={register("highest_qualification")}
              placeholder="e.g., MSc, BSc, PhD"
            />
            <InputWithLabel
              label="Years of Professional Experience"
              register={register("years_of_pro_expe")}
              placeholder="e.g., 5 years"
            />
            <InputWithLabel
              label="Current Job Title"
              register={register("present_job_title")}
              placeholder="Enter your current job title"
            />

            <div className="mb-6">
              <h3 className="text-lg font-medium text-gray-800 mb-2">
                Supporting Documents
              </h3>
              <p className="text-sm text-gray-600 mb-4">
                Please upload relevant certifications or documents to support
                your application.
              </p>
              <InputWithLabel
                label="Upload Certifications"
                register={register("certifications")}
                type="file"
                multiple
              />
            </div>

            <button
              type="submit"
              disabled={isLoading}
              className={`text-white bg-primary hover:bg-primary/90 focus:ring-4 focus:outline-none focus:ring-primary/30 font-medium rounded-lg text-sm w-full px-5 py-2.5 text-center flex items-center justify-center ${
                isLoading ? "opacity-70 cursor-not-allowed" : ""
              }`}
            >
              {isLoading ? (
                <>
                  <svg
                    className="animate-spin -ml-1 mr-3 h-5 w-5 text-white"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="none"
                    viewBox="0 0 24 24"
                  >
                    <circle
                      className="opacity-25"
                      cx="12"
                      cy="12"
                      r="10"
                      stroke="currentColor"
                      strokeWidth="4"
                    ></circle>
                    <path
                      className="opacity-75"
                      fill="currentColor"
                      d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"
                    ></path>
                  </svg>
                  Submitting...
                </>
              ) : (
                "Submit Application"
              )}
            </button>

            <p className="mt-4 text-sm text-black text-center">
              By submitting this form, you agree to our membership terms and
              conditions. Your application will be reviewed, and you will
              receive a confirmation email at the provided address.
            </p>
          </form>
        </Layout>
      </main>
    </div>
  );
};

export default BecomeAMember;
